### ISSUE TITLE
Out of string memory error [170+ MB CSV]

### ISSUE THREAD

**Issue by ws-garcia** [Senipah/VBA-DynamicArray#6] opened 2020-11-27 17:24 UTC
**Is your feature request related to a problem?** 
YES

**Please describe.**
Dear @Senipah, it’s me, AGAIN! I was testing the CSV Interface class trying to find the memory limits of it and, in the same path of work, check if the change from `String` array to `Variant` jagged array has the potential to make the class run out of memory for a CSV file of couple of megabytes of size. 
I used both your solution and sdkn's as benchmarks. The test’s objective was invoking the import procedure, bypassing the result in the case of @sdkn104, and avoiding copies of arrays in the case of your project and mine, so that the imported data was only present in the class members.
As a result of the above, I get a surprising error when invoke yours ` FromCSVString` method. It’s about the error 14: “Out of string space”. 

**Describe the solution you'd like**
The question here is only one: it’s possible to deal with the memory consumption, when working with `String` data type, for your solution? 

**Additional context**
Attached to this I let you the file used as “guinea pig” ([Demo_1.6MM_records.zip](https://github.com/Senipah/VBA-Better-Array/files/5609022/Demo_1.6MM_records.zip)), hoping you can find the error source, and, additional to that, some screen shoots with the memory usage for both, @sdkn104 and mine, solutions.

NOTE: **due to file size, the Demo_1.6MM_records.zip contains a .7z file inside**.

![Out of string space](https://user-images.githubusercontent.com/70865364/100472983-b17d7300-30b3-11eb-958e-6ca84e37300b.png)

![sdkn Memory usage](https://user-images.githubusercontent.com/70865364/100473001-be01cb80-30b3-11eb-9556-f9920eb79bd7.png)

![CSV Interface Memory usage](https://user-images.githubusercontent.com/70865364/100473002-bf32f880-30b3-11eb-854f-f990571acde5.png)

**Comment by Senipah** [comment] 2020-11-27 18:47
I am able to parse that file using my `FromCSVFile` method. See the below screenshot:
![image](https://user-images.githubusercontent.com/4821959/100477579-92490a80-30e0-11eb-9826-1e5bfabeb551.png)

If you upload the file you were testing in for me to take a look at I will do so but at the moment its a "works for me" situation, especially if I can't repro and it sounds like you have edited my class in some way(?).

If I cant reproduce I'll have to close the issue but as I say happy to take a look at any file you have.

**Comment by Senipah** [comment] 2020-11-27 19:09
I assume your issue is that the peak memory usage exceeds 4GB. I assume you are running a 32Bit application and therefore run out of available RAM?

![Untitled](https://user-images.githubusercontent.com/4821959/100478665-cbcf4500-30e3-11eb-94de-e224be9271dd.png)

**Comment by ws-garcia** [comment] 2020-11-27 19:15
>it sounds like you have edited my class in some way(?)

Your class module is untouched.

Here is the code I'm using
```vb
Sub SENIPAHtest(ByVal filePath As String)
    Dim Senipah As BetterArray
    Dim csv As CSVinterface
    Dim CSVdata As String
    Dim avg As Double
    Dim e As Double, f As Double
    
    'Test SENIPAH method
    Set csv = New CSVinterface
    CSVdata = csv.GetDataFromCSV(filePath)
    Set csv = Nothing
    Set Senipah = New BetterArray
    avg = 0
    e = Timer
    Call Senipah.FromCSVString(CSVdata)
    f = Timer
    avg = avg + CDbl(f - e)
    Set Senipah = Nothing
    Debug.Print "[Senipah FromCSVString:"; Round(avg, 4); "seconds]"
End Sub
```

And here using the `FromCSVFile` method

```vb
Sub SENIPAHtest(ByVal filePath As String)
    Dim Senipah As BetterArray
    Dim avg As Double
    Dim e As Double, f As Double
    
    'Test SENIPAH method
    Set Senipah = New BetterArray
    avg = 0
    e = Timer
    Call Senipah.FromCSVFile(filePath)
    f = Timer
    avg = avg + CDbl(f - e)
    Set Senipah = Nothing
    Debug.Print "[Senipah FromCSVString:"; Round(avg, 4); "seconds]"
End Sub
```

Now I'm getting a "Out of memory error" on a machine running **Win 10 x64**, with **8GB RAM**, **Excel 2019 32bits**. I'm still surprised!

![Out of memory](https://user-images.githubusercontent.com/70865364/100479001-59e70380-30c3-11eb-8839-2a58a6f16f90.png)

![Senipah Memory usage](https://user-images.githubusercontent.com/70865364/100479002-5a7f9a00-30c3-11eb-906b-8f57a581a160.png)

**Comment by ws-garcia** [comment] 2020-11-27 19:19
> 
> 
> I assume your issue is that the peak memory usage exceeds 4GB. I assume you are running a 32Bit application and therefore run out of available RAM?
> 
> ![Untitled](https://user-images.githubusercontent.com/4821959/100478665-cbcf4500-30e3-11eb-94de-e224be9271dd.png)

This can be the problem here.

**Comment by ws-garcia** [comment] 2020-11-27 19:24
>The question here is only one: it’s possible to deal with the memory consumption, when working with String data type, for your solution?

I think there is nothing to do with my issue!

**Comment by Senipah** [comment] 2020-11-27 19:38
Alright, so it sounds like the issue is that because mine uses more auxiliary memory while parsing that 1.6m row file than is available to 32Bit Excel. 

Out of interest I converted mine to return a string array rather than store a variant array in the class and that did bring it's peak usage below 4GB. Downloadable here: [StringCSVTest.zip](https://github.com/Senipah/VBA-Better-Array/files/5609342/StringCSVTest.zip)
![Untitled](https://user-images.githubusercontent.com/4821959/100479691-d8a16800-30e6-11eb-9fa5-49dd960553c1.png)

While my solution uses more auxiliary memory than yours and the other solution you benchmark against I am a bit unwilling to refactor this method any more at this time as I think that the chance of anyone in the real world seeking to parse a file that large using my class is both unlikely and ill-advised. As you know, CSV parsing isn't my library's main focus: it exists as a utility, and it does that job acceptably at the moment I think.

That said, If you have any suggestions or want to submit a PR to try and improve the performance of my parser (while maintaining the functionality of the class as a whole) I am definitely willing to review.

**Closed as completed by Senipah** 2020-11-27 19:38 UTC
Labels: enhancement

**Comment by ws-garcia** [comment] 2020-11-27 20:08
>and it does that job acceptably at the moment I think.

Your parser do the parsing task in a outstanding way! The variations in the CSV syntax don't affect its performance and, for me, this is stunning!
